#![allow(dead_code)]

/* automatically generated by rust-bindgen 0.59.2 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lnDisplay {
    pub _address: u8,
}
extern "C" {
    #[link_name = "\u{1}_ZN9lnDisplay4initEv"]
    pub fn lnDisplay_init();
}
extern "C" {
    #[link_name = "\u{1}_ZN9lnDisplay17displayMaxCurrentEi"]
    pub fn lnDisplay_displayMaxCurrent(currentMa: cty::c_int);
}
extern "C" {
    #[link_name = "\u{1}_ZN9lnDisplay6bannerEPKc"]
    pub fn lnDisplay_banner(msg: *const cty::c_char);
}
extern "C" {
    #[link_name = "\u{1}_ZN9lnDisplay11displayVbatEf"]
    pub fn lnDisplay_displayVbat(vbat: f32);
}
extern "C" {
    #[link_name = "\u{1}_ZN9lnDisplay14displayCurrentEi"]
    pub fn lnDisplay_displayCurrent(ma: cty::c_int);
}
extern "C" {
    #[link_name = "\u{1}_ZN9lnDisplay14displayVoltageEbf"]
    pub fn lnDisplay_displayVoltage(cc: bool, voltage: f32);
}
extern "C" {
    #[link_name = "\u{1}_ZN9lnDisplay12displayPowerEbf"]
    pub fn lnDisplay_displayPower(cc: bool, pw: f32);
}
extern "C" {
    #[link_name = "\u{1}_ZN9lnDisplay9benchmarkEv"]
    pub fn lnDisplay_benchmark();
}
impl lnDisplay {
    #[inline]
    pub unsafe fn init() {
        lnDisplay_init()
    }
    #[inline]
    pub unsafe fn displayMaxCurrent(currentMa: cty::c_int) {
        lnDisplay_displayMaxCurrent(currentMa)
    }
    #[inline]
    pub unsafe fn banner(msg: *const cty::c_char) {
        lnDisplay_banner(msg)
    }
    #[inline]
    pub unsafe fn displayVbat(vbat: f32) {
        lnDisplay_displayVbat(vbat)
    }
    #[inline]
    pub unsafe fn displayCurrent(ma: cty::c_int) {
        lnDisplay_displayCurrent(ma)
    }
    #[inline]
    pub unsafe fn displayVoltage(cc: bool, voltage: f32) {
        lnDisplay_displayVoltage(cc, voltage)
    }
    #[inline]
    pub unsafe fn displayPower(cc: bool, pw: f32) {
        lnDisplay_displayPower(cc, pw)
    }
    #[inline]
    pub unsafe fn benchmark() {
        lnDisplay_benchmark()
    }
}
