
SET(USE_CLANG True CACHE INTERNAL "")
SET(LN_ENABLE_RUST ON CACHE INTERNAL "")
SET(LN_ENABLE_I2C  ON CACHE INTERNAL "")
SET(LN_ENABLE_SPI  ON CACHE INTERNAL "")
SET(LN_DEBUG_UART 1 CACHE INTERNAL "")
SET(LN_ENABLE_USBD FALSE CACHE INTERNAL "")

#SET(USE_CH32V3x        True CACHE INTERNAL "")
#SET(USE_CH32v3x_HW_IRQ_STACK TRUE CACHE INTERNAL "")
SET(USE_48PIN_PACKAGE True CACHE INTERNAL "")
SET(USE_GD32F3      TRUE CACHE INTERNAL "")


#SET(LN_LTO "-flto"  CACHE INTERNAL "")
