
SET(USE_CLANG True CACHE INTERNAL "")
SET(LN_ENABLE_RUST ON CACHE INTERNAL "")
SET(LN_ENABLE_I2C  ON CACHE INTERNAL "")
SET(LN_ENABLE_SPI  ON CACHE INTERNAL "")
SET(LN_DEBUG_UART 1 CACHE INTERNAL "")
SET(LN_ENABLE_USBD FALSE CACHE INTERNAL "")
#SET(LN_USB_NB_CDC  0 CACHE INTERNAL "")
#SET(LN_USB_NB_HID  0 CACHE INTERNAL "")
#SET(LN_USB_DFU_RUNTIME 0 CACHE INTERNAL "")

#SET(USE_RP2040        True CACHE INTERNAL "")
#SET(USE_RP_ZERO        True CACHE INTERNAL "")
#SET(USE_RP_CARRIER        True CACHE INTERNAL "")

#SET(USE_CH32V3x        True CACHE INTERNAL "")
#SET(USE_CH32v3x_HW_IRQ_STACK TRUE CACHE INTERNAL "")
#SET(USE_HW_FPU         TRUE CACHE INTERNAL "")

#SET(USE_GD32F3      TRUE CACHE INTERNAL "")

#SET(LN_LTO "-flto"  CACHE INTERNAL "")
